In [ ]:
#importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#importing the dataset
data = pd.read_csv('https://raw.githubusercontent.com/NetzwerkPriyanka8/ML_April/main/Projects/Logistic_Regression/Social_Network_Ads.csv')
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
#initiating the variables
X = data.drop(['Purchased'], axis = 1)
y = data['Purchased'].values.reshape(-1,1)


In [ ]:
#splitting the data into training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X , y, test_size=0.2, random_state=42)

In [ ]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
#training our model using Logistic Regression
from sklearn.linear_model import LogisticRegression
classfr = LogisticRegression()
classfr.fit(X_train, y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
#testing our model
y_pred = classfr.predict(X_test)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [ ]:
#making the confusion matrix 
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[50  2]
 [ 9 19]]


0.8625

In [ ]:
#Prediction for new values
out = classfr.predict([[30, 87000]])
out

array([1])

In [ ]:
out = classfr.predict([[15, 1000]])
out

array([1])

In [ ]:
#Taking the input from the user
print("enter the corresponding details :")
Age = float(input("Age :"))
EstimatedSalary = float(input("Salary :"))

output = classfr.predict([[Age, EstimatedSalary]])
print("The predicion of purchased acc. to that is {} on the basis of Age {} and EstimatedSalary {}".format(output[0] if output else "No data",Age, EstimatedSalary))

enter the corresponding details :
Age :22
Salary :50000
The predicion of purchased acc. to that is 1 on the basis of Age 22.0 and EstimatedSalary 50000.0
