#Importing the libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy import stats

#Reading the data

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/NetzwerkPriyanka8/ML_April/main/Projects/Linear_Regression/Advertising_data.csv')

#Displaying the first 5 rows of dataset

In [3]:
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   2210
1   44.5   39.3       45.1   1040
2   17.2   45.9       69.3    930
3  151.5   41.3       58.5   1850
4  180.8   10.8       58.4   1290

#Displaying the last 5 rows of dataset

In [4]:
df.tail()

TV  radio  newspaper  sales
195   38.2    3.7       13.8    760
196   94.2    4.9        8.1    970
197  177.0    9.3        6.4   1280
198  283.6   42.0       66.2   2550
199  232.1    8.6        8.7   1340

#Initiating the variables


In [14]:
X = df.drop(['sales'], axis = 1)
y = df['sales'].values.reshape(-1,1)
X

TV  radio  newspaper
0    230.1   37.8       69.2
1     44.5   39.3       45.1
2     17.2   45.9       69.3
3    151.5   41.3       58.5
4    180.8   10.8       58.4
..     ...    ...        ...
195   38.2    3.7       13.8
196   94.2    4.9        8.1
197  177.0    9.3        6.4
198  283.6   42.0       66.2
199  232.1    8.6        8.7

[200 rows x 3 columns]

In [15]:
X = df.drop(['sales'], axis = 1)
y = df['sales'].values.reshape(-1,1)
y

array([[2210],
       [1040],
       [ 930],
       [1850],
       [1290],
       [ 720],
       [1180],
       [1320],
       [ 480],
       [1060],
       [ 860],
       [1740],
       [ 920],
       [ 970],
       [1900],
       [2240],
       [1250],
       [2440],
       [1130],
       [1460],
       [1800],
       [1250],
       [ 560],
       [1550],
       [ 970],
       [1200],
       [1500],
       [1590],
       [1890],
       [1050],
       [2140],
       [1190],
       [ 960],
       [1740],
       [ 950],
       [1280],
       [2540],
       [1470],
       [1010],
       [2150],
       [1660],
       [1710],
       [2070],
       [1290],
       [ 850],
       [1490],
       [1060],
       [2320],
       [1480],
       [ 970],
       [1140],
       [1070],
       [2260],
       [2120],
       [2020],
       [2370],
       [ 550],
       [1320],
       [2380],
       [1840],
       [ 810],
       [2420],
       [1570],
       [1400],
       [1800],
       [ 930],
       [ 9

#Splitting data into training, testing datase


In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Fitting Linear regression to our training set


In [17]:
from sklearn.linear_model import LinearRegression
multiple_reg = LinearRegression()
multiple_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

#Predicting the test set result

In [23]:
y_pred = multiple_reg.predict(X_test)

##Calculating the coefficients


In [24]:
multiple_reg.coef_

array([[ 4.47295175, 18.91950542,  0.27611143]])

#Calculating the intercept

In [26]:
multiple_reg.intercept_

array([297.90673381])

#Calculating the R squared value


In [27]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.899438024100912

#Prediction for new values

In [28]:
#Taking the input from the user
print("Enter the ammount you will invest on:")
tv = float(input("TV : "))
radio = float(input("Radio : "))
newspaper = float(input("Newspaper : "))

#predicting the sales with respect to the inputs
output = multiple_reg.predict([[tv,radio,newspaper]])
print("you will get Rs{:.2f} sales by advertising Rs{} on TV, Rs{} on Radio and Rs{} on newspaper."\
      .format(output[0][0] if output else "not predictable",tv,radio,newspaper))

Enter the ammount you will invest on:
TV : 500
Radio : 200
Newspaper : 10
you will get Rs6321.04 sales by advertising Rs500.0 on TV, Rs200.0 on Radio and Rs10.0 on newspaper.


In [29]:
#Taking the input from the user
print("Enter the ammount you will invest on:")
tv = float(input("TV : "))
radio = float(input("Radio : "))
newspaper = float(input("Newspaper : "))

#predicting the sales with respect to the inputs
output = multiple_reg.predict([[tv,radio,newspaper]])
print("you will get Rs{:.2f} sales by advertising Rs{} on TV, Rs{} on Radio and Rs{} on newspaper."\
      .format(output[0][0] if output else "not predictable",tv,radio,newspaper))

Enter the ammount you will invest on:
TV : 1034.6
Radio : 554.6
Newspaper : 344.2
you will get Rs15513.42 sales by advertising Rs1034.6 on TV, Rs554.6 on Radio and Rs344.2 on newspaper.
