#Importing The Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy import stats

#Reading the dataset

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/NetzwerkPriyanka8/ML_April/main/Final_Project/50_startups_data.csv")
df.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

In [4]:
df.tail()

R&D Spend  Administration  Marketing Spend    Profit
45    1000.23       124153.04          1903.93  64926.08
46    1315.46       115816.21        297114.46  49490.75
47       0.00       135426.92             0.00  42559.73
48     542.05        51743.15             0.00  35673.41
49       0.00       116983.80         45173.06  14681.40

#Checking for any missing values in dataset

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   Profit           50 non-null     float64
dtypes: float64(4)
memory usage: 1.7 KB


In [7]:
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
Profit             0
dtype: int64

No any missing values in entire dataset.

#Discription of dataset

In [8]:
df.describe()

R&D Spend  Administration  Marketing Spend         Profit
count      50.000000       50.000000        50.000000      50.000000
mean    73721.615600   121344.639600    211025.097800  112012.639200
std     45902.256482    28017.802755    122290.310726   40306.180338
min         0.000000    51283.140000         0.000000   14681.400000
25%     39936.370000   103730.875000    129300.132500   90138.902500
50%     73051.080000   122699.795000    212716.240000  107978.190000
75%    101602.800000   144842.180000    299469.085000  139765.977500
max    165349.200000   182645.560000    471784.100000  192261.830000

#Initiating the variables

In [9]:
X = df.drop(['Profit'], axis = 1)
y = df['Profit'].values.reshape(-1,1)
X

R&D Spend  Administration  Marketing Spend
0   165349.20       136897.80        471784.10
1   162597.70       151377.59        443898.53
2   153441.51       101145.55        407934.54
3   144372.41       118671.85        383199.62
4   142107.34        91391.77        366168.42
5   131876.90        99814.71        362861.36
6   134615.46       147198.87        127716.82
7   130298.13       145530.06        323876.68
8   120542.52       148718.95        311613.29
9   123334.88       108679.17        304981.62
10  101913.08       110594.11        229160.95
11  100671.96        91790.61        249744.55
12   93863.75       127320.38        249839.44
13   91992.39       135495.07        252664.93
14  119943.24       156547.42        256512.92
15  114523.61       122616.84        261776.23
16   78013.11       121597.55        264346.06
17   94657.16       145077.58        282574.31
18   91749.16       114175.79        294919.57
19   86419.70       153514.11             0.00
20   76253.86       113867.30        298664.47
21   78389.47       153773.43        299737.29
22   73994.56       122782.75        303319.26
23   67532.53       105751.03        304768.73
24   77044.01        99281.34        140574.81
25   64664.71       139553.16        137962.62
26   75328.87       144135.98        134050.07
27   72107.60       127864.55        353183.81
28   66051.52       182645.56        118148.20
29   65605.48       153032.06        107138.38
30   61994.48       115641.28         91131.24
31   61136.38       152701.92         88218.23
32   63408.86       129219.61         46085.25
33   55493.95       103057.49        214634.81
34   46426.07       157693.92        210797.67
35   46014.02        85047.44        205517.64
36   28663.76       127056.21        201126.82
37   44069.95        51283.14        197029.42
38   20229.59        65947.93        185265.10
39   38558.51        82982.09        174999.30
40   28754.33       118546.05        172795.67
41   27892.92        84710.77        164470.71
42   23640.93        96189.63        148001.11
43   15505.73       127382.30         35534.17
44   22177.74       154806.14         28334.72
45    1000.23       124153.04          1903.93
46    1315.46       115816.21        297114.46
47       0.00       135426.92             0.00
48     542.05        51743.15             0.00
49       0.00       116983.80         45173.06

In [10]:
X = df.drop(['Profit'], axis = 1)
y = df['Profit'].values.reshape(-1,1)
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

#Splitting the data into training and testing dataset

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Fitting Multiple Linear Regression to training set

In [12]:
from sklearn.linear_model import LinearRegression
multiple_reg = LinearRegression()
multiple_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

#Predicting the testing dataset result

In [14]:
y_pred = multiple_reg.predict(X_test)
y_pred

array([[126703.02716461],
       [ 84894.75081556],
       [ 98893.41815974],
       [ 46501.70815036],
       [129128.39734381],
       [ 50992.69486261],
       [109016.5536578 ],
       [100878.4641454 ],
       [ 97700.59638629],
       [113106.15292226]])

#Calculating the coefficients

In [15]:
multiple_reg.coef_

array([[ 0.80377928, -0.06792917,  0.03124155]])

#Calculating the intercept

In [16]:
multiple_reg.intercept_

array([54071.87574599])

#Calculating R-squared value to get Accuracy 

In [17]:
from sklearn.metrics import r2_score
r2_score(y_test , y_pred)*100            # into 100 because to get accuracy in percentage

90.00653083037321

#Prediction for new values

In [18]:
output = multiple_reg.predict([[350000.5 , 234569.77 , 8877654.60]])
output

array([[596812.54703434]])

In [19]:
output = multiple_reg.predict([[992345.6 , 3325464.55 , 1129894.60]])
output

array([[661102.29724109]])

#Prediction by taking input from User for new values

In [34]:
print("Enter the amount you have spend on:")
RDSpend = float(input("R & D Spend : "))
Administration = float(input("Adminisration : "))
MarketingSpend = float(input("Marketing Spend : "))

#predicting the Profit with respect to the all spending inputs
output = multiple_reg.predict([[RDSpend, Administration, MarketingSpend]])
print("you will get Rs {} Profit by spending Rs {} on R & D , Rs {} on Adminisration and Rs {} on Marketing."\
      .format(output[0][0] if output else "not predictable",RDSpend, Administration, MarketingSpend))

Enter the amount you have spend on:
R & D Spend : 1554978.5
Adminisration : 344596.77
Marketing Spend : 239997.7
you will get Rs 1288021.0933060453 Profit by spending Rs 1554978.5 on R & D , Rs 344596.77 on Adminisration and Rs 239997.7 on Marketing.


In [35]:
print("Enter the amount you have spend on:")
RDSpend = float(input("R & D Spend : "))
Administration = float(input("Adminisration : "))
MarketingSpend = float(input("Marketing Spend : "))

#predicting the Profit with respect to the all spending inputs
output = multiple_reg.predict([[RDSpend, Administration, MarketingSpend]])
print("you will get Rs {} Profit by spending Rs {} on R & D , Rs {} on Adminisration and Rs {} on Marketing."\
      .format(output[0][0] if output else "not predictable",RDSpend, Administration, MarketingSpend))

Enter the amount you have spend on:
R & D Spend : 566667.665
Adminisration : 565442.77
Marketing Spend : 100768.52
you will get Rs 474285.70507390075 Profit by spending Rs 566667.665 on R & D , Rs 565442.77 on Adminisration and Rs 100768.52 on Marketing.
